name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: Build with dotnet
      run: dotnet build --configuration Release
    - name: Publish NuGet
      run: dotnet pack ./Zxw.Framework.NetCore/Zxw.Framework.NetCore.csproj --configuration Release
    - name: Pack
      run: dotnet nuget push "./Zxw.Framework.NetCore/bin/Release/Zxw.Framework.NetCore.3.1.3.2.nupkg" --source "https://nuget.pkg.github.com/VictorTzeng/index.json"
